# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-gosec-ubuntu:
        build:
            args:
                - BASE_IMAGE=ubuntu:focal
            context: docker/
            dockerfile: GoSec-Ubuntu.dockerfile
        container_name: pds-gosec-ubuntu
        env_file:
            - .env
        networks:
            - "sechub"

networks:
    sechub:
        external: true
        name: "sechub"
